### ISSUE TITLE
Exception not caught during initial lock request

### ISSUE THREAD

**Issue by maunzCache** [mohankishore/python_dynamodb_lock#1770]
* Python DynamoDB Lock version: 0.91
* Python version: 3.8.10
* Operating System: Windows 10 with WSL 2 Ubuntu 20.04

### Description
I was starting to try this code for locking

```python
def lock(table_name: TableName, lock_id: str, meta_data: dict):
    '''
    :param table_name: TODO
    :param lock_id: TODO
    :param meta_data: TODO
    '''

    # get a reference to the DynamoDB resource
    dynamodb_resource = boto3.resource('dynamodb')

    # create the lock-client
    lock_client = DynamoDBLockClient(dynamodb_resource, table_name.value)

    # Note: We don't need the lock because we leave the python runtime to execute terragrunt
    lock = lock_client.acquire_lock(lock_id, additional_attributes=meta_data)

    # close the lock_client
    lock_client.close(release_locks=False)`
```

Which is basically copy & paste from the docs. Started up python and was greeted by an exception after running it on an empty DynamoDB table

```
Traceback (most recent call last):
  File "/.venv/lib/lib/python3.8/site-packages/python_dynamodb_lock/python_dynamodb_lock.py", line 425, in acquire_lock
    existing_lock = self._get_lock_from_dynamodb(partition_key, sort_key)
  File "/.venv/lib/lib/python3.8/site-packages/python_dynamodb_lock/python_dynamodb_lock.py", line 564, in _get_lock_from_dynamodb
    result = self._dynamodb_table.get_item(
  File "/.venv/lib/lib/python3.8/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/.venv/lib/lib/python3.8/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/.venv/lib/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/.venv/lib/lib/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetItem operation: Requested resource not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./toolchain/lib/mutex.py", line 71, in <module>
    main(args)
  File "./toolchain/lib/mutex.py", line 47, in main
    lock(mutex_type, mutex_id, meta_data)
  File "/lib/cicd/__init__.py", line 27, in lock
    lock = lock_client.acquire_lock(lock_id, additional_attributes=meta_data)
  File "/.venv/lib/lib/python3.8/site-packages/python_dynamodb_lock/python_dynamodb_lock.py", line 467, in acquire_lock
    raise DynamoDBLockError(DynamoDBLockError.UNKNOWN, str(e))
python_dynamodb_lock.python_dynamodb_lock.DynamoDBLockError: DynamoDBLockError: UNKNOWN - An error occurred (ResourceNotFoundException) when calling the GetItem operation: Requested resource not found
```

The problem can be found in that line
https://github.com/mohankishore/python_dynamodb_lock/blob/master/python_dynamodb_lock/python_dynamodb_lock.py#L425

The call does is to try to look up a potentially existing lock to see if we have to steal the lock or create a new one. Because in an empty table no lock exists, this will throw the ResourceNotFoundException from the AWS API which is not caught by the code.

Also the implementation of an initial get does not make sense to me because we want to have atomic operations and can simply use a conditional put (which is already implemented). As reference i got [this article](https://blog.revolve.team/2020/09/08/implement-mutex-with-dynamodb/) sent from my AWS TAM

Either i don't understand how it works or it cannot work at all :(

**Comment by maunzCache** [comment]
Was simply not cool enough to select the correct AWS account for the DB to be found. Still the other bug resides.
