### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by paulca99** [mohankishore/python_dynamodb_lock#197]
* Python DynamoDB Lock version:latest
* Python version:2.7
* Operating System:MacOS / Amazaon Linux 2

### Description

Just import the module causes error:-

Traceback (most recent call last):
  File "zoo-init.py", line 9, in <module>
    from python_dynamodb_lock.python_dynamodb_lock import *
  File "/usr/local/lib/python2.7/site-packages/python_dynamodb_lock/python_dynamodb_lock.py", line 17, in <module>
    from urllib.parse import quote
ImportError: No module named parse

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by tkang007** [comment]
Hi, Is there any plan to support python2 ?
